### ISSUE TITLE
woa-project.dev or similar as the website domain for the DuoWOA and LumiaWOA websites?

### ISSUE THREAD

**Issue by abrendan** [WOA-Project/DuoWOA#1]
Hello everyone!

I would love to contribute to DuoWOA and I thought about a real direct domain for this project. Either a general domain for the WOA project or two for DuoWOA and LumiaWOA. Would that be interesting? I would pay for the chosen domains. 

Thank you for all the work!

Brendan

**Comment by gus33000** [comment]
Hi!

Thanks for the offer,

We already had a domain before, however, we struggle to find anything to put on here and we also struggle to be active to maintain a separate website.

So i don't think we would accept this offer. Currently github &/ github.io is just fine for us.
